name = "nk2telco-domains"
compatibility_date = "2025-08-28"

# Note: This file is used only for wrangler commands that need a project manifest.
# Cloudflare DNS bulk operations rely on the Cloudflare account associated with your login.

[env.production]
# zone_id = "YOUR_ZONE_ID"
# account_id = "YOUR_ACCOUNT_ID"

# Optional: define a worker route if you want to attach a worker to api.nk2telco.com.au
# [[routes]]
# pattern = "api.nk2telco.com.au/*"
# script = "your-worker-name"
