name = "securecart"
compatibility_date = "2025-08-28"

[pages]
pages_build_output_dir = "./dist"

[build]
command = "npm run build"
directory = "dist"

# Optional account/zone information for production environment
[env.production]
# account_id = "YOUR_ACCOUNT_ID"
# zone_id = "YOUR_ZONE_ID"

# Note: Cloudflare Pages Functions live in the `functions/` directory in your project root.
# Do NOT add runtime JS to this TOML file; keep only configuration here.
